trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Ansible@0
  inputs:
    ansibleInterface: 'remoteMachine'
    connectionOverSsh: 'SSH - Ansible VM'
    playbookSourceRemoteMachine: 'agentMachine'
    playbookRootRemoteMachine: '/home/azureuser'
    playbookPathLinkedArtifactOnRemoteMachine: 'users.yml'
    inventoriesRemoteMachine: 'file'
    inventoryFileSourceRemoteMachine: 'agentMachine'
    inventoryFileLinkedArtifactOnRemoteMachine: 'inventory.yml'
    args: '--private-key ~/.ssh/ansible_rsa'